In [1]:
import torch
from prob_mbrl import envs, utils, models

In [2]:
exp = utils.ExperienceDataset()
exp.load("/home/juancamilog/.prob_mbrl/results_DoubleCartpole_20181123112356.149824.pth.tar")

# initialize env
env = envs.DoubleCartpole()
env.dt = env.model.dt
D = env.observation_space.shape[0]
U = env.action_space.shape[0]
maxU = env.action_space.high

# initalize policy
pol_shape = [50]*2
pol_model = models.mlp(
        D, U, pol_shape,
        dropout_layers=[models.modules.BDropout(0.1)
                        for i in range(len(pol_shape))],
        nonlin=torch.nn.ReLU,
        weights_initializer=torch.nn.init.xavier_normal_,
        biases_initializer=None,
        output_nonlin=torch.nn.Tanh)

pol = models.Policy(pol_model, maxU).float()

In [3]:
values = []
for it, pol_params in enumerate(exp.policy_parameters):
    if len(pol_params) == 0:
        continue
    print it
    for p, p_data in zip(pol.parameters(), pol_params):
        p.data  = p_data
    cb = lambda *args, **kwargs: env.render()
    values_it = []
    for i in range(10):
        ret = utils.apply_controller(env, pol, 60, callback=cb, realtime=False)
        values_it.append(sum(ret[2]))
        print values_it[-1]
    values.append(values_it)
values = torch.tensor(values)

10
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [2.909190]
tensor([[2.9092]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [4.227519]
tensor([[4.2275]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [4.877907]
tensor([[4.8779]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [3.489995]
tensor([[3.4900]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [2.776214]
tensor([[2.7762]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [2.840556]
tensor([[2.8406]])
apply_controller Starting run
apply_controller Ru

apply_controller Done. Stopping robot. Value of run [6.807744]
tensor([[6.8077]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [7.452351]
tensor([[7.4524]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [7.122416]
tensor([[7.1224]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [11.032943]
tensor([[11.0329]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [5.672894]
tensor([[5.6729]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [7.099261]
tensor([[7.0993]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of ru

apply_controller Done. Stopping robot. Value of run [9.742045]
tensor([[9.7420]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [5.061412]
tensor([[5.0614]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [15.432560]
tensor([[15.4326]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [4.029543]
tensor([[4.0295]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [8.167167]
tensor([[8.1672]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [5.037600]
tensor([[5.0376]])
21
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of

apply_controller Done. Stopping robot. Value of run [6.439463]
tensor([[6.4395]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [9.571892]
tensor([[9.5719]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [8.000312]
tensor([[8.0003]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [10.522781]
tensor([[10.5228]])
26
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [7.411473]
tensor([[7.4115]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of run [3.580115]
tensor([[3.5801]])
apply_controller Starting run
apply_controller Running for 3.000000 seconds
apply_controller Done. Stopping robot. Value of